<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ur_cbf_bringup</name>
  <version>0.1.7</version>
  <description>Launch files para os backends Gazebo e Universal Robots real do projeto CBF.</description>
  <maintainer email="cayoalmeida0@users.noreply.github.com">Cayo Sousa</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ur_robot_driver</exec_depend>
  <exec_depend>ur_simulation_gz</exec_depend>

  <test_depend>ament_pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
